namespace SHENZENSolitaire
{
    public enum Deck : byte
    {
        Empty,
        Red1,
        Red2,
        Red3,
        Red4,
        Red5,
        Red6,
        Red7,
        Red8,
        Red9,
        Black1,
        Black2,
        Black3,
        Black4,
        Black5,
        Black6,
        Black7,
        Black8,
        Black9,
        Green1,
        Green2,
        Green3,
        Green4,
        Green5,
        Green6,
        Green7,
        Green8,
        Green9,
        Rose,
        Red,
        Black,
        Green,
        Invalid
    }
}
